"""initial_schema

Revision ID: 537a85a77311
Revises: 
Create Date: 2026-03-31 17:17:39.857100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '537a85a77311'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_campaigns',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('persona', sa.Text(), nullable=True),
    sa.Column('segment', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='drafted', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leads_email_lower', 'leads', ['email'], unique=True, postgresql_using='btree')
    op.create_table('sender_accounts',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=True),
    sa.Column('warmup_status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), server_default='smartlead', nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('headers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dedupe_key', sa.String(length=500), nullable=True),
    sa.Column('processing_status', sa.String(length=50), server_default='received', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_receipts_dedupe_key'), 'webhook_receipts', ['dedupe_key'], unique=False)
    op.create_table('campaign_deliveries',
    sa.Column('internal_campaign_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), server_default='smartlead', nullable=False),
    sa.Column('provider_campaign_id', sa.String(length=255), nullable=True),
    sa.Column('sender_account_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='created', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['internal_campaign_id'], ['internal_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_account_id'], ['sender_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaign_deliveries_internal_campaign_id', 'campaign_deliveries', ['internal_campaign_id'], unique=False)
    op.create_index('ix_campaign_deliveries_provider_campaign_id', 'campaign_deliveries', ['provider_campaign_id'], unique=False)
    op.create_table('campaign_lead_links',
    sa.Column('campaign_delivery_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('provider_lead_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_delivery_id'], ['campaign_deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaign_lead_links_delivery_id', 'campaign_lead_links', ['campaign_delivery_id'], unique=False)
    op.create_index('ix_campaign_lead_links_lead_id', 'campaign_lead_links', ['lead_id'], unique=False)
    op.create_index('uq_campaign_lead_links_delivery_lead', 'campaign_lead_links', ['campaign_delivery_id', 'lead_id'], unique=True)
    op.create_table('outbound_messages',
    sa.Column('campaign_link_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('message_status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_link_id'], ['campaign_lead_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbound_messages_campaign_link_id', 'outbound_messages', ['campaign_link_id'], unique=False)
    op.create_index('ix_outbound_messages_provider_message_id', 'outbound_messages', ['provider_message_id'], unique=False)
    op.create_index('ix_outbound_messages_status', 'outbound_messages', ['message_status'], unique=False)
    op.create_index('uq_outbound_messages_link_step', 'outbound_messages', ['campaign_link_id', 'step_number'], unique=True)
    op.create_table('message_events',
    sa.Column('outbound_message_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['outbound_message_id'], ['outbound_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_events_event_time', 'message_events', ['event_time'], unique=False)
    op.create_index('ix_message_events_event_type', 'message_events', ['event_type'], unique=False)
    op.create_index('ix_message_events_outbound_message_id', 'message_events', ['outbound_message_id'], unique=False)
    op.create_index('uq_message_events_provider_event', 'message_events', ['outbound_message_id', 'provider_event_id'], unique=True, postgresql_where='provider_event_id IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_message_events_provider_event', table_name='message_events', postgresql_where='provider_event_id IS NOT NULL')
    op.drop_index('ix_message_events_outbound_message_id', table_name='message_events')
    op.drop_index('ix_message_events_event_type', table_name='message_events')
    op.drop_index('ix_message_events_event_time', table_name='message_events')
    op.drop_table('message_events')
    op.drop_index('uq_outbound_messages_link_step', table_name='outbound_messages')
    op.drop_index('ix_outbound_messages_status', table_name='outbound_messages')
    op.drop_index('ix_outbound_messages_provider_message_id', table_name='outbound_messages')
    op.drop_index('ix_outbound_messages_campaign_link_id', table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index('uq_campaign_lead_links_delivery_lead', table_name='campaign_lead_links')
    op.drop_index('ix_campaign_lead_links_lead_id', table_name='campaign_lead_links')
    op.drop_index('ix_campaign_lead_links_delivery_id', table_name='campaign_lead_links')
    op.drop_table('campaign_lead_links')
    op.drop_index('ix_campaign_deliveries_provider_campaign_id', table_name='campaign_deliveries')
    op.drop_index('ix_campaign_deliveries_internal_campaign_id', table_name='campaign_deliveries')
    op.drop_table('campaign_deliveries')
    op.drop_index(op.f('ix_webhook_receipts_dedupe_key'), table_name='webhook_receipts')
    op.drop_table('webhook_receipts')
    op.drop_table('sender_accounts')
    op.drop_index('ix_leads_email_lower', table_name='leads', postgresql_using='btree')
    op.drop_table('leads')
    op.drop_table('internal_campaigns')
    # ### end Alembic commands ###
